import { invoke } from "@tauri-apps/api/core";
import type { Account, ApplicationKind, ApplicationStatus, CodexSession, CodexSessionMessage, CursorUsageDetails, GrokBotStatus, LocalSession, LocalSessionMessage, McpServer, Plugin, SessionDeleteBatchResult, AttachmentAvailability} from "./types";

export const listApplications = () => invoke<ApplicationStatus[]>("list_applications");
export const listAccounts = (kind: ApplicationKind) => invoke<Account[]>("list_accounts", { kind });
export const listGrokBotAccounts = () => invoke<Account[]>("list_grok_bot_accounts");
export const refreshGrokBotAccounts = () => invoke<{ total: number; failed: number; invalid: number; missing: number; blocked?: number }>("refresh_grok_bot_accounts");
export const getDatabasePath = () => invoke<string>("get_database_path");
export const moveDatabase = (directory: string) => invoke<string>("move_database", { directory });
export const exportDatabase = (file: string) => invoke<void>("export_database", { file });
export const importDatabase = (file: string) => invoke<string>("import_database", { file });
export const getPreserveCodexOfficialAuth = () => invoke<boolean>("get_preserve_codex_official_auth");
export const setPreserveCodexOfficialAuth = (enabled: boolean) => invoke<void>("set_preserve_codex_official_auth", { enabled });
export const listCursorPlugins = () => invoke<Plugin[]>("list_cursor_plugins");
export const listCodexPlugins = () => invoke<Plugin[]>("list_codex_plugins");
export const listGrokPlugins = () => invoke<Plugin[]>("list_grok_plugins");
export const listCodexSessions = () => invoke<CodexSession[]>("list_codex_sessions");
export const getCodexSessionMessages = (id: string) => invoke<CodexSessionMessage[]>("get_codex_session_messages", { id });
export const deleteCodexSession = (id: string) => invoke<void>("delete_codex_session", { id });
export const deleteCodexSessions = (ids: string[]) => invoke<SessionDeleteBatchResult>("delete_codex_sessions", { ids });
export const launchCursor = () => invoke<void>("launch_cursor");
export const launchChatgpt = () => invoke<void>("launch_chatgpt");
export const launchGrokBot = () => invoke<void>("launch_grok_bot");
export const launchCodexSession = (id: string) => invoke("launch_codex_session", { id });
export const listGrokSessions = () => invoke<LocalSession[]>("list_grok_sessions");
export const getGrokSessionMessages = (id: string) => invoke<LocalSessionMessage[]>("get_grok_session_messages", { id });
export const deleteGrokSession = (id: string) => invoke<void>("delete_grok_session", { id });
export const deleteGrokSessions = (ids: string[]) => invoke<SessionDeleteBatchResult>("delete_grok_sessions", { ids });
export const launchGrokSession = (id: string) => invoke("launch_grok_session", { id });
export const getGrokBotExportRecord = (id: string) => invoke<unknown>("get_grok_bot_export_record", { id });
export const getGrokBotStatus = () => invoke<GrokBotStatus>("get_grok_bot_status");
export const getCursorUsage = (id: string) => invoke<CursorUsageDetails>("get_cursor_usage", { id });
export const getGrokUsage = (id: string) => invoke<CursorUsageDetails>("get_grok_usage", { id });
export const getSavedGrokUsage = (id: string) => invoke<CursorUsageDetails | null>("get_saved_grok_usage", { id });
export const openExternalUrl = (url: string) => invoke<void>("open_external_url", { url });
export const listGrokBotSessions = () => invoke<LocalSession[]>("list_grok_bot_sessions");
export const getGrokBotSessionMessages = (id: string) => invoke<LocalSessionMessage[]>("get_grok_bot_session_messages", { id });
export const deleteGrokBotSession = (id: string) => invoke<void>("delete_grok_bot_session", { id });
export const deleteGrokBotSessions = (ids: string[]) => invoke<SessionDeleteBatchResult>("delete_grok_bot_sessions", { ids });
export const renameGrokBotSession = (id: string, title: string) => invoke<void>("rename_grok_bot_session", { id, title });
export const listCursorSessions = () => invoke<LocalSession[]>("list_cursor_sessions");
export const getCursorSessionMessages = (id: string) => invoke<LocalSessionMessage[]>("get_cursor_session_messages", { id });
export const deleteCursorSession = (id: string) => invoke<void>("delete_cursor_session", { id });
export const deleteCursorSessions = (ids: string[]) => invoke<SessionDeleteBatchResult>("delete_cursor_sessions", { ids });
export const setCodexPluginEnabled = (id: string, enabled: boolean) => invoke("set_codex_plugin_enabled", { id, enabled });
export const setCodexPluginCapabilityEnabled = (pluginId: string, capabilityId: string, kind: "skill" | "mcp", enabled: boolean) => invoke("set_codex_plugin_capability_enabled", { pluginId, capabilityId, kind, enabled });
export const deleteCodexPlugin = (id: string) => invoke("delete_codex_plugin", { id });
export const setGrokPluginEnabled = (id: string, enabled: boolean) => invoke("set_grok_plugin_enabled", { id, enabled });
export const deleteGrokPlugin = (id: string) => invoke("delete_grok_plugin", { id });
export const listMcpServers = (kind: ApplicationKind) => invoke<McpServer[]>("list_mcp_servers", { kind });
export const setMcpServerEnabled = (kind: ApplicationKind, id: string, enabled: boolean) => invoke("set_mcp_server_enabled", { kind, id, enabled });
export const setCursorPluginEnabled = (id: string, source: Plugin["source"], enabled: boolean) => invoke("set_cursor_plugin_enabled", { id, source, enabled });
export const deleteCursorPlugin = (id: string, source: Plugin["source"]) => invoke("delete_cursor_plugin", { id, source });

export const exportSessionAttachment = (source: string, destination: string) =>
  invoke<void>("export_session_attachment", { source, destination });
export const readSessionAttachmentPreview = (source: string) =>
  invoke<string | null>("read_session_attachment_preview", { source });
export const checkSessionAttachmentAvailability = (source: string) =>
  invoke<AttachmentAvailability>("check_session_attachment_availability", { source });
