import { invoke } from "@tauri-apps/api/core";
import type { Account, ApplicationKind, ApplicationStatus, CodexSession, CodexSessionMessage, DownloadJob, LocalLlm, LocalSession, LocalSessionMessage, McpServer, ModelFormat, ModelSource, Plugin, RemoteModelFile, RemoteModelHit, RemoteModelProbe, SessionDeleteBatchResult } from "./types";

export const listApplications = () => invoke<ApplicationStatus[]>("list_applications");
export const listAccounts = (kind: ApplicationKind) => invoke<Account[]>("list_accounts", { kind });
export const getDatabasePath = () => invoke<string>("get_database_path");
export const moveDatabase = (directory: string) => invoke<string>("move_database", { directory });
export const exportDatabase = (file: string) => invoke<void>("export_database", { file });
export const importDatabase = (file: string) => invoke<string>("import_database", { file });
export const getPreserveCodexOfficialAuth = () => invoke<boolean>("get_preserve_codex_official_auth");
export const setPreserveCodexOfficialAuth = (enabled: boolean) => invoke<void>("set_preserve_codex_official_auth", { enabled });
export const getHfTokenConfigured = () => invoke<boolean>("get_hf_token_configured");
export const setHfToken = (token: string) => invoke<void>("set_hf_token", { token });
export const listCursorPlugins = () => invoke<Plugin[]>("list_cursor_plugins");
export const listCodexPlugins = () => invoke<Plugin[]>("list_codex_plugins");
export const listGrokPlugins = () => invoke<Plugin[]>("list_grok_plugins");
export const listCodexSessions = () => invoke<CodexSession[]>("list_codex_sessions");
export const getCodexSessionMessages = (id: string) => invoke<CodexSessionMessage[]>("get_codex_session_messages", { id });
export const deleteCodexSession = (id: string) => invoke<void>("delete_codex_session", { id });
export const deleteCodexSessions = (ids: string[]) => invoke<SessionDeleteBatchResult>("delete_codex_sessions", { ids });
export const launchCodexSession = (id: string) => invoke("launch_codex_session", { id });
export const listGrokSessions = () => invoke<LocalSession[]>("list_grok_sessions");
export const getGrokSessionMessages = (id: string) => invoke<LocalSessionMessage[]>("get_grok_session_messages", { id });
export const deleteGrokSession = (id: string) => invoke<void>("delete_grok_session", { id });
export const deleteGrokSessions = (ids: string[]) => invoke<SessionDeleteBatchResult>("delete_grok_sessions", { ids });
export const launchGrokSession = (id: string) => invoke("launch_grok_session", { id });
export const listCursorSessions = () => invoke<LocalSession[]>("list_cursor_sessions");
export const getCursorSessionMessages = (id: string) => invoke<LocalSessionMessage[]>("get_cursor_session_messages", { id });
export const deleteCursorSession = (id: string) => invoke<void>("delete_cursor_session", { id });
export const deleteCursorSessions = (ids: string[]) => invoke<SessionDeleteBatchResult>("delete_cursor_sessions", { ids });
export const setCodexPluginEnabled = (id: string, enabled: boolean) => invoke("set_codex_plugin_enabled", { id, enabled });
export const setCodexPluginCapabilityEnabled = (pluginId: string, capabilityId: string, kind: "skill" | "mcp", enabled: boolean) => invoke("set_codex_plugin_capability_enabled", { pluginId, capabilityId, kind, enabled });
export const deleteCodexPlugin = (id: string) => invoke("delete_codex_plugin", { id });
export const setGrokPluginEnabled = (id: string, enabled: boolean) => invoke("set_grok_plugin_enabled", { id, enabled });
export const deleteGrokPlugin = (id: string) => invoke("delete_grok_plugin", { id });
export const listMcpServers = (kind: ApplicationKind) => invoke<McpServer[]>("list_mcp_servers", { kind });
export const setMcpServerEnabled = (kind: ApplicationKind, id: string, enabled: boolean) => invoke("set_mcp_server_enabled", { kind, id, enabled });
export const setCursorPluginEnabled = (id: string, source: Plugin["source"], enabled: boolean) => invoke("set_cursor_plugin_enabled", { id, source, enabled });
export const deleteCursorPlugin = (id: string, source: Plugin["source"]) => invoke("delete_cursor_plugin", { id, source });
export const searchRemoteModels = (source: ModelSource, query: string, format?: ModelFormat) => invoke<RemoteModelHit[]>("search_remote_models", { source, query, format: format && format !== "all" ? format : null });
export const probeRemoteModel = (source: ModelSource, repo: string, revision?: string) => invoke<RemoteModelProbe>("probe_remote_model", { source, repo, revision: revision || null });
export const startModelDownload = (source: ModelSource, repo: string, revision?: string, files?: string[]) => invoke<string>("start_model_download", { source, repo, revision: revision || null, files: files ?? null });
export const startModelDownloadFast = (source: ModelSource, repo: string, revision: string, files: RemoteModelFile[]) => invoke<string>("start_model_download_fast", { source, repo, revision, files });
export const cancelModelDownload = (jobId: string) => invoke("cancel_model_download", { jobId });
export const listDownloadJobs = () => invoke<DownloadJob[]>("list_download_jobs");
export const resumeDownloadJob = (jobId: string) => invoke("resume_download_job", { jobId });
export const dismissDownloadJob = (jobId: string) => invoke("dismiss_download_job", { jobId });
export const listLocalModels = () => invoke<LocalLlm[]>("list_local_models");
export const refreshLocalModels = () => invoke<LocalLlm[]>("refresh_local_models");
export const reorderLocalModels = (ids: string[]) => invoke("reorder_local_models", { ids });
export const deleteLocalModel = (id: string) => invoke("delete_local_model", { id });
export const openLocalModelDir = (id: string) => invoke("open_local_model_dir", { id });
export const migrateLocalModel = (id: string, target: ModelSource) => invoke<void>("migrate_local_model", { id, target });
